### create a site
POST http://localhost:8080/sites
content-type: application/json

{
  "name": "onej",
  "displayName": " JAV torrent",
  "crawlerType": 1
}


### Create a catalog
POST http://localhost:8080/api/v1/catalogs
content-type: application/json

{
  "siteId": "65ed2c8a59521477e4eeadb0",
  "name": "北野未奈",
  "url": "https://ffjav.com/torrent/tag/%E5%8C%97%E9%87%8E%E6%9C%AA%E5%A5%88"
}


### submit a task running for catalog page
POST http://localhost:8080/api/v1/tasks/catalog-pages
Content-Type: application/json

{
  "catalogId": "661fb9d1460d64048fba4cbc",
  "url": "https://ffjav.com/torrent/tag/%E5%8C%97%E9%87%8E%E6%9C%AA%E5%A5%88/page/16"
}


### submit a novel task
POST http://localhost:8080/tasks/novels
Content-Type: application/json

{
  "catalogId": "65ed2cba59521477e4eeadb1",
  "url": "https://.com/actress/Fuua%20Kaede?page=89"
}
