### create a site
POST http://localhost:8080/sites
content-type: application/json

{
  "name": "nsf",
  "displayName": "nsf图书馆",
  "crawlerType": 3,
  "attributes": {
    "siteUrl": "https://www.nosadfun.com"
  }
}


### Create a catalog
POST http://localhost:8080/catalogs
content-type: application/json

{
  "siteId": "64fc0401b28d6f3158b0ebf1",
  "name": "辣文",
  "url": "https://www.nosadfun.com/category/8/",
  "crawlerType": 3
}


### submit a task running for catalog page
POST http://localhost:8080/tasks/catalog-pages
Content-Type: application/json

{
  "catalogId": "64fc0417b28d6f3158b0ebf2",
  "url": "https://www.nosadfun.com/category/2/1-5.html"
}


### submit a novel task
POST http://localhost:8080/tasks/novels
Content-Type: application/json

{
  "catalogId": "64fc0417b28d6f3158b0ebf2",
  "url": "https://www.nosadfun.com/book/26573/"
}
