
http:
  port: 8080


## end in page 40
crawlerSettings:
  catalogPageTaskParallelism: 1
  novelTaskParallelism: 2
  chapterTaskParallelism: 5
  excludedNovelUrls:
    - https://kxkmh.top/manga/1203
    - https://kxkmh.top/manga/1844
    - https://kxkmh.top/manga/1197
    - https://kxkmh.top/manga/1918
    - https://kxkmh.top/manga/1835/detail/61673
    - https://kxkmh.top/manga/1143
    - https://kxkmh.top/manga/1043
    - https://kxkmh.top/manga/1775
    - https://kxkmh.top/manga/1058
    - https://kxkmh.top/manga/1123
    - https://kxkmh.top/manga/1857
    - https://kxkmh.top/manga/1369
    - https://kxkmh.top/manga/1058/detail/36137
    - https://kxkmh.top/manga/1196/detail/40716
    - https://kxkmh.top/manga/1041/detail/35412
    - https://kxkmh.top/manga/1060
    - https://kxkmh.top/manga/1202
    - https://kxkmh.top/manga/1044
    - https://kxkmh.top/manga/70
    - https://kxkmh.top/manga/1178
    - https://kxkmh.top/manga/287
    - https://kxkmh.top/manga/1189
    - https://kxkmh.top/manga/1815
    - https://kxkmh.top/manga/1154
    - https://kxkmh.top/manga/1856
    - https://kxkmh.top/manga/286
    - https://kxkmh.top/manga/1731
    - https://kxkmh.top/manga/1174
    - https://kxkmh.top/manga/1105
    - https://kxkmh.top/manga/1179
    - https://kxkmh.top/manga/1685
    - https://kxkmh.top/manga/1045
    - https://kxkmh.top/manga/1069
    - https://kxkmh.top/manga/1506
    - https://kxkmh.top/manga/1327
    - https://kxkmh.top/manga/1106
    - https://kxkmh.top/manga/118
    - https://kxkmh.top/manga/732
    - https://kxkmh.top/manga/1623
    - https://kxkmh.top/manga/1115
    - https://kxkmh.top/manga/186
    - https://kxkmh.top/manga/659
    - https://kxkmh.top/manga/1062
    - https://kxkmh.top/manga/1068
    - https://kxkmh.top/manga/718
    - https://kxkmh.top/manga/1869
    - https://kxkmh.top/manga/1063
    - https://kxkmh.top/manga/1089
    - https://kxkmh.top/manga/603
    - https://kxkmh.top/manga/988
    - https://kxkmh.top/manga/593
#    - https://github.com/
